---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ditvtvtvt/payments
    argocd-image-updater.argoproj.io/payments.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: payments-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ssh://git@github.com:DITVTVTVT/k8s.git
    targetRevision: main
    path: helm-charts/payments
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: "ditvtvtvt/payments"
        - name: "image.tag"
          value: "0.1.0"
        - name: "service.port"
          value: "8080"
        - name: "livenessProbe.httpGet.path"
          value: "/healthz"
        - name: "readinessProbe.httpGet.path"
          value: "/healthz"